### ISSUE TITLE
No issue, only 1 advice & 1 wish

### ISSUE THREAD

**Issue by zymase** [0xSobky/AnonTab#1]
I'm running flawlessly _AnonTab_ 1.5.4 on _Firefox_ 50.0.2 64-BIT on _Windows_ 7 64-BIT.

One advice for users of the _uBlock_ add-on : you have to add AnonTab to _**uBlock's Whitelist**_:

> ananontab.resource-scheme

One wish, that of having an _Open Bookmark in AnonTab_ in the same way we have _Open Link in AnonTab_

**Comment by 0xSobky** [comment]
I have added a [note](https://github.com/0xSobky/AnonTab#notes) in the _README_ page for users of the µBlock (and uBlock Origin) browser extension(s).

And as for the _Open Bookmark in AnonTab_ option, I will consider adding it in the next releases.

Thank you!
