### ISSUE TITLE
AnonTab 1.6.1 at AMO (sandbox) stated as corrupt upon install

### ISSUE THREAD

**Issue by zymase** [0xSobky/AnonTab#2]
I was unable to install latest AnonTab 1.6.1 from its AMO page, still sandboxed,
https://addons.mozilla.org/en-US/firefox/addon/anontab/versions/

Install is refused and displays anontab-1.6.1-an+fx.xpi as _corrupt_.

**Comment by 0xSobky** [comment]
Hi @zymase,

That particular version is a migration to [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) which is only supported on very recent versions of Firefox. Once the review process is completed, you should be able to install it without problems on the latest version of Firefox.

But if you wish to try it right away, you can download the _anontab-1.6.1-an+fx.xpi_ executable and install it manually by visiting  `about:debugging` then click `Load Temporary Add-on`.

Thanks,
