### ISSUE TITLE
Other servers than "feedback.googleusercontent.com"

### ISSUE THREAD

**Issue by ghost** [0xSobky/AnonTab#3]
Hi,

On AnonTab's AMO page is stated :

> By default, AnonTab connects to "feedback.googleusercontent.com" in order to mask external requests; however, this can be easily configured from the settings page.

I of course understand how to access the settings page but what I ignore is finding an alternative to this default _"feedback.googleusercontent.com"_

Could you provide just a few alternatives you consider viable?

Thanks.

**Comment by 0xSobky** [comment]
Hi @StanGets,

I'm afraid I don't currently have alternatives to that proxy. However, if you have some basic programming experience, you could probably build a simple one yourself using free available resources/services.

If you decide to go down that path, please keep in mind that you'll need to [allow cross-origin requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) to your proxy.

Leaving this issue open as I might find some time to implement a backup proxy in the future....

**Comment by StanGets** [comment]
OK, thanks @0xSobky 
I'm afraid I don't have sufficient basic programming experience to build an alternative. I'll stay tuned to this (non) issue of course.

**Comment by 0xSobky** [comment]
I've added a new proxy in the latest update ([/AnonTab/blob/master/src/data/scripts/main.js#L7](https://github.com/0xSobky/AnonTab/blob/master/src/data/scripts/main.js#L7)).

I think we can close this issue now as resolved :-)

**Comment by pflegende** [comment]
seems the extension does no longer work for opera.

---



![Anon_JSErr_Opera Momentaufnahme_2022-06-10_144903_chrome-extension](https://user-images.githubusercontent.com/52720420/173069377-83ec5406-5715-4f47-8244-5241788f221c.png)

---

May be, allorigins is not transparent for js.

---

A workaround may be to use your new proxy

`https://api.allorigins.win/raw?url=`

direct in adressbar.

But
"totally off the record browsing."
is no more available.
Only the first delivery of the called urls is proxified.
After this all klicks generates calls from the "native" host without anonymising.

---

I saw that you no longer maintain the project. So don't be angry.
Should only be a mention of the good project and a hint for other users.

🍨 today!
CU
