### ISSUE TITLE
AnonTab suddenly cannot connect (NetworkError)

### ISSUE THREAD

**Issue by muspench** [0xSobky/AnonTab#4]
Hello! My AnonTab installation worked very well until a few days ago, when connection became intermittent and then stopped altogether, throwing NetworkError on each attempt.

I set my Windows 7 to an older restore point, which had no effect.

Did a new install of Firefox using the instructions here: https://support.mozilla.org/en-US/questions/1247610 , which gave me a new profile (no old addons, history, etc.).

Installed AnonTab as the sole addon, and AnonTab still can't connect. I think I've eliminated a number of possible causes, but I don't know where to go from here?

Thanks very much for any suggestions on how to fix it, because I really like using AnonTab.

**Comment by 0xSobky** [comment]
Fixed, thank you for filing this issue (and sorry you had to go into too much trouble trying to figure out what is wrong with the extension).

The problem was with the Google proxy used to fetch external content, so I had to change it. Please file a new issue if you encounter any other problems :-)

**Comment by muspench** [comment]
Wow, that was fast! Thank you so much for the fix, and I didn't at all mind doing the troubleshooting (eliminates the risk of feeling stupid when I ask for help). :)

Much appreciated, because I love using AnonTab.
 
 -----Original Message-----
